': This program was generated by
': InForm - GUI system for QB64 - Beta version 3
': Fellippe Heitor, 2016 - fellippe@qb64.org - @fellippeheitor
'-----------------------------------------------------------

': Controls' IDs: ------------------------------------------------------------------
DIM SHARED TextEditorWindow AS LONG
DIM SHARED MenuFrame AS LONG
DIM SHARED SpritesFrame AS LONG
DIM SHARED ZincName AS LONG
DIM SHARED Label2 AS LONG
DIM SHARED Label3 AS LONG
DIM SHARED Label4 AS LONG
DIM SHARED Feedback AS LONG
DIM SHARED SpriteList AS LONG
DIM SHARED SpriteName AS LONG
DIM SHARED SpriteLB AS LONG
DIM SHARED variablesFrame AS LONG
DIM SHARED AddGlobalVariable AS LONG
DIM SHARED DelVariable AS LONG
DIM SHARED GlobalVarName AS LONG
DIM SHARED PublicVarList AS LONG
DIM SHARED AddGlobalVariable2 AS LONG
DIM SHARED AddGlobalVariable3 AS LONG
DIM SHARED PrivVarList AS LONG
DIM SHARED PrivVarName AS LONG
DIM SHARED AddGlobalList AS LONG
DIM SHARED DelList AS LONG
DIM SHARED Breaker AS LONG
DIM SHARED GlobalVarName2 AS LONG
DIM SHARED PublicVarList2 AS LONG
DIM SHARED EditorFrame AS LONG

': External modules: ---------------------------------------------------------------
'$INCLUDE:'InForm\InForm.ui'
'$INCLUDE:'InForm\xp.uitheme'
'$INCLUDE:'TextEditorWindow.frm'

': Event procedures: ---------------------------------------------------------------
SUB __UI_BeforeInit

END SUB

SUB __UI_OnLoad

END SUB

SUB __UI_BeforeUpdateDisplay

END SUB

SUB __UI_BeforeUnload

END SUB

SUB __UI_Click (id AS LONG)
    SELECT CASE id
        CASE TextEditorWindow

        CASE MenuFrame

        CASE SpritesFrame

        CASE ZincName

        CASE Label2

        CASE Label3

        CASE Label4

        CASE Feedback

        CASE SpriteList

        CASE SpriteName

        CASE SpriteLB

        CASE variablesFrame

        CASE AddGlobalVariable

        CASE DelVariable

        CASE GlobalVarName

        CASE PublicVarList

        CASE AddGlobalVariable2

        CASE AddGlobalVariable3

        CASE PrivVarList

        CASE PrivVarName

        CASE AddGlobalList

        CASE DelList

        CASE Breaker

        CASE GlobalVarName2

        CASE PublicVarList2

        CASE EditorFrame

    END SELECT
END SUB

SUB __UI_MouseEnter (id AS LONG)
    SELECT CASE id
        CASE TextEditorWindow

        CASE MenuFrame

        CASE SpritesFrame

        CASE ZincName

        CASE Label2

        CASE Label3

        CASE Label4

        CASE Feedback

        CASE SpriteList

        CASE SpriteName

        CASE SpriteLB

        CASE variablesFrame

        CASE AddGlobalVariable

        CASE DelVariable

        CASE GlobalVarName

        CASE PublicVarList

        CASE AddGlobalVariable2

        CASE AddGlobalVariable3

        CASE PrivVarList

        CASE PrivVarName

        CASE AddGlobalList

        CASE DelList

        CASE Breaker

        CASE GlobalVarName2

        CASE PublicVarList2

        CASE EditorFrame

    END SELECT
END SUB

SUB __UI_MouseLeave (id AS LONG)
    SELECT CASE id
        CASE TextEditorWindow

        CASE MenuFrame

        CASE SpritesFrame

        CASE ZincName

        CASE Label2

        CASE Label3

        CASE Label4

        CASE Feedback

        CASE SpriteList

        CASE SpriteName

        CASE SpriteLB

        CASE variablesFrame

        CASE AddGlobalVariable

        CASE DelVariable

        CASE GlobalVarName

        CASE PublicVarList

        CASE AddGlobalVariable2

        CASE AddGlobalVariable3

        CASE PrivVarList

        CASE PrivVarName

        CASE AddGlobalList

        CASE DelList

        CASE Breaker

        CASE GlobalVarName2

        CASE PublicVarList2

        CASE EditorFrame

    END SELECT
END SUB

SUB __UI_FocusIn (id AS LONG)
    SELECT CASE id
        CASE SpriteList

        CASE SpriteName

        CASE AddGlobalVariable

        CASE DelVariable

        CASE GlobalVarName

        CASE PublicVarList

        CASE AddGlobalVariable2

        CASE AddGlobalVariable3

        CASE PrivVarList

        CASE PrivVarName

        CASE AddGlobalList

        CASE DelList

        CASE GlobalVarName2

        CASE PublicVarList2

    END SELECT
END SUB

SUB __UI_FocusOut (id AS LONG)
    SELECT CASE id
        CASE SpriteList

        CASE SpriteName

        CASE AddGlobalVariable

        CASE DelVariable

        CASE GlobalVarName

        CASE PublicVarList

        CASE AddGlobalVariable2

        CASE AddGlobalVariable3

        CASE PrivVarList

        CASE PrivVarName

        CASE AddGlobalList

        CASE DelList

        CASE GlobalVarName2

        CASE PublicVarList2

    END SELECT
END SUB

SUB __UI_MouseDown (id AS LONG)
    SELECT CASE id
        CASE TextEditorWindow

        CASE MenuFrame

        CASE SpritesFrame

        CASE ZincName

        CASE Label2

        CASE Label3

        CASE Label4

        CASE Feedback

        CASE SpriteList

        CASE SpriteName

        CASE SpriteLB

        CASE variablesFrame

        CASE AddGlobalVariable

        CASE DelVariable

        CASE GlobalVarName

        CASE PublicVarList

        CASE AddGlobalVariable2

        CASE AddGlobalVariable3

        CASE PrivVarList

        CASE PrivVarName

        CASE AddGlobalList

        CASE DelList

        CASE Breaker

        CASE GlobalVarName2

        CASE PublicVarList2

        CASE EditorFrame

    END SELECT
END SUB

SUB __UI_MouseUp (id AS LONG)
    SELECT CASE id
        CASE TextEditorWindow

        CASE MenuFrame

        CASE SpritesFrame

        CASE ZincName

        CASE Label2

        CASE Label3

        CASE Label4

        CASE Feedback

        CASE SpriteList

        CASE SpriteName

        CASE SpriteLB

        CASE variablesFrame

        CASE AddGlobalVariable

        CASE DelVariable

        CASE GlobalVarName

        CASE PublicVarList

        CASE AddGlobalVariable2

        CASE AddGlobalVariable3

        CASE PrivVarList

        CASE PrivVarName

        CASE AddGlobalList

        CASE DelList

        CASE Breaker

        CASE GlobalVarName2

        CASE PublicVarList2

        CASE EditorFrame

    END SELECT
END SUB

SUB __UI_KeyPress (id AS LONG)
    SELECT CASE id
        CASE SpriteList

        CASE SpriteName

        CASE AddGlobalVariable

        CASE DelVariable

        CASE GlobalVarName

        CASE PublicVarList

        CASE AddGlobalVariable2

        CASE AddGlobalVariable3

        CASE PrivVarList

        CASE PrivVarName

        CASE AddGlobalList

        CASE DelList

        CASE GlobalVarName2

        CASE PublicVarList2

    END SELECT
END SUB

SUB __UI_TextChanged (id AS LONG)
    SELECT CASE id
        CASE SpriteName

        CASE GlobalVarName

        CASE PrivVarName

        CASE GlobalVarName2

    END SELECT
END SUB

SUB __UI_ValueChanged (id AS LONG)
    SELECT CASE id
        CASE SpriteList

        CASE PublicVarList

        CASE PrivVarList

        CASE PublicVarList2

    END SELECT
END SUB

