': This program was generated by
': InForm - GUI system for QB64 - Beta version 3
': Fellippe Heitor, 2016 - fellippe@qb64.org - @fellippeheitor
'-----------------------------------------------------------

': Controls' IDs: ------------------------------------------------------------------
DIM SHARED begin AS LONG
DIM SHARED ProgressBar1 AS LONG

': External modules: ---------------------------------------------------------------
'$INCLUDE:'InForm\InForm.ui'
'$INCLUDE:'InForm\xp.uitheme'
'$INCLUDE:'begin.frm'

': Event procedures: ---------------------------------------------------------------
SUB __UI_BeforeInit

END SUB

SUB __UI_OnLoad
RUN "Execute.bat"
END SUB

SUB __UI_BeforeUpdateDisplay

END SUB

SUB __UI_BeforeUnload

END SUB

SUB __UI_Click (id AS LONG)
SELECT CASE id
    CASE begin

    CASE ProgressBar1

END SELECT
END SUB

SUB __UI_MouseEnter (id AS LONG)
SELECT CASE id
    CASE begin

    CASE ProgressBar1

END SELECT
END SUB

SUB __UI_MouseLeave (id AS LONG)
SELECT CASE id
    CASE begin

    CASE ProgressBar1

END SELECT
END SUB

SUB __UI_FocusIn (id AS LONG)
SELECT CASE id
END SELECT
END SUB

SUB __UI_FocusOut (id AS LONG)
SELECT CASE id
END SELECT
END SUB

SUB __UI_MouseDown (id AS LONG)
SELECT CASE id
    CASE begin

    CASE ProgressBar1

END SELECT
END SUB

SUB __UI_MouseUp (id AS LONG)
SELECT CASE id
    CASE begin

    CASE ProgressBar1

END SELECT
END SUB

SUB __UI_KeyPress (id AS LONG)
SELECT CASE id
END SELECT
END SUB

SUB __UI_TextChanged (id AS LONG)
SELECT CASE id
END SELECT
END SUB

SUB __UI_ValueChanged (id AS LONG)
SELECT CASE id
END SELECT
END SUB

