': This program was generated by
': InForm - GUI system for QB64 - Beta version 3
': Fellippe Heitor, 2016 - fellippe@qb64.org - @fellippeheitor
'-----------------------------------------------------------

': Controls' IDs: ------------------------------------------------------------------
DIM SHARED NewProjectWindow AS LONG
DIM SHARED Frame1 AS LONG
DIM SHARED Label1 AS LONG
DIM SHARED TextBox1 AS LONG
DIM SHARED Button1 AS LONG
DIM SHARED Label2 AS LONG
DIM SHARED TextBox2 AS LONG
DIM SHARED LicenseRadio AS LONG
DIM SHARED PublicRadio AS LONG
DIM SHARED LicenseList AS LONG
DIM SHARED CheckBoxEnc AS LONG
DIM SHARED encryptInput AS LONG
DIM SHARED Create AS LONG
DIM SHARED CancelButton AS LONG
DIM SHARED LicenseButton AS LONG

': External modules: ---------------------------------------------------------------
'$INCLUDE:'InForm\InForm.ui'
'$INCLUDE:'InForm\xp.uitheme'
'$INCLUDE:'NewProjectWindow.frm'

': Event procedures: ---------------------------------------------------------------
SUB __UI_BeforeInit

END SUB

SUB __UI_OnLoad

END SUB

SUB __UI_BeforeUpdateDisplay

END SUB

SUB __UI_BeforeUnload

END SUB

SUB __UI_Click (id AS LONG)
SELECT CASE id
    CASE NewProjectWindow

    CASE Frame1

    CASE Label1

    CASE TextBox1

    CASE Button1

    CASE Label2

    CASE TextBox2

    CASE LicenseRadio

    CASE PublicRadio

    CASE LicenseList

    CASE CheckBoxEnc

    CASE encryptInput

    CASE Create

    CASE CancelButton

    CASE LicenseButton

END SELECT
END SUB

SUB __UI_MouseEnter (id AS LONG)
SELECT CASE id
    CASE NewProjectWindow

    CASE Frame1

    CASE Label1

    CASE TextBox1

    CASE Button1

    CASE Label2

    CASE TextBox2

    CASE LicenseRadio

    CASE PublicRadio

    CASE LicenseList

    CASE CheckBoxEnc

    CASE encryptInput

    CASE Create

    CASE CancelButton

    CASE LicenseButton

END SELECT
END SUB

SUB __UI_MouseLeave (id AS LONG)
SELECT CASE id
    CASE NewProjectWindow

    CASE Frame1

    CASE Label1

    CASE TextBox1

    CASE Button1

    CASE Label2

    CASE TextBox2

    CASE LicenseRadio

    CASE PublicRadio

    CASE LicenseList

    CASE CheckBoxEnc

    CASE encryptInput

    CASE Create

    CASE CancelButton

    CASE LicenseButton

END SELECT
END SUB

SUB __UI_FocusIn (id AS LONG)
SELECT CASE id
    CASE TextBox1

    CASE Button1

    CASE TextBox2

    CASE LicenseRadio

    CASE PublicRadio

    CASE LicenseList

    CASE CheckBoxEnc

    CASE encryptInput

    CASE Create

    CASE CancelButton

    CASE LicenseButton

END SELECT
END SUB

SUB __UI_FocusOut (id AS LONG)
SELECT CASE id
    CASE TextBox1

    CASE Button1

    CASE TextBox2

    CASE LicenseRadio

    CASE PublicRadio

    CASE LicenseList

    CASE CheckBoxEnc

    CASE encryptInput

    CASE Create

    CASE CancelButton

    CASE LicenseButton

END SELECT
END SUB

SUB __UI_MouseDown (id AS LONG)
SELECT CASE id
    CASE NewProjectWindow

    CASE Frame1

    CASE Label1

    CASE TextBox1

    CASE Button1

    CASE Label2

    CASE TextBox2

    CASE LicenseRadio

    CASE PublicRadio

    CASE LicenseList

    CASE CheckBoxEnc

    CASE encryptInput

    CASE Create

    CASE CancelButton
        STOP
    CASE LicenseButton

END SELECT
END SUB

SUB __UI_MouseUp (id AS LONG)
SELECT CASE id
    CASE NewProjectWindow

    CASE Frame1

    CASE Label1

    CASE TextBox1

    CASE Button1

    CASE Label2

    CASE TextBox2

    CASE LicenseRadio

    CASE PublicRadio

    CASE LicenseList

    CASE CheckBoxEnc

    CASE encryptInput

    CASE Create

    CASE CancelButton

    CASE LicenseButton

END SELECT
END SUB

SUB __UI_KeyPress (id AS LONG)
SELECT CASE id
    CASE TextBox1

    CASE Button1

    CASE TextBox2

    CASE LicenseRadio

    CASE PublicRadio

    CASE LicenseList

    CASE CheckBoxEnc

    CASE encryptInput

    CASE Create

    CASE CancelButton

    CASE LicenseButton

END SELECT
END SUB

SUB __UI_TextChanged (id AS LONG)
SELECT CASE id
    CASE TextBox1

    CASE TextBox2

    CASE encryptInput

END SELECT
END SUB

SUB __UI_ValueChanged (id AS LONG)
SELECT CASE id
    CASE LicenseList

END SELECT
END SUB

