': This program was generated by
': InForm - GUI system for QB64 - Beta version 3
': Fellippe Heitor, 2016 - fellippe@qb64.org - @fellippeheitor
'-----------------------------------------------------------

': Controls' IDs: ------------------------------------------------------------------
DIM SHARED LicensesWindow AS LONG
DIM SHARED Label1 AS LONG
DIM SHARED InformLicView AS LONG
DIM SHARED Label2 AS LONG
DIM SHARED QB64LicViewPg AS LONG
DIM SHARED ZincLicense AS LONG
DIM SHARED InformLicView2 AS LONG

': External modules: ---------------------------------------------------------------
'$INCLUDE:'InForm\InForm.ui'
'$INCLUDE:'InForm\xp.uitheme'
'$INCLUDE:'LicensesWindow.frm'

': Event procedures: ---------------------------------------------------------------
SUB __UI_BeforeInit

END SUB

SUB __UI_OnLoad

END SUB

SUB __UI_BeforeUpdateDisplay

END SUB

SUB __UI_BeforeUnload

END SUB

SUB __UI_Click (id AS LONG)
    SELECT CASE id
        CASE LicensesWindow

        CASE Label1

        CASE InformLicView

        CASE Label2

        CASE QB64LicViewPg

        CASE ZincLicense

        CASE InformLicView2

    END SELECT
END SUB

SUB __UI_MouseEnter (id AS LONG)
    SELECT CASE id
        CASE LicensesWindow

        CASE Label1

        CASE InformLicView

        CASE Label2

        CASE QB64LicViewPg

        CASE ZincLicense

        CASE InformLicView2

    END SELECT
END SUB

SUB __UI_MouseLeave (id AS LONG)
    SELECT CASE id
        CASE LicensesWindow

        CASE Label1

        CASE InformLicView

        CASE Label2

        CASE QB64LicViewPg

        CASE ZincLicense

        CASE InformLicView2

    END SELECT
END SUB

SUB __UI_FocusIn (id AS LONG)
    SELECT CASE id
        CASE InformLicView

        CASE QB64LicViewPg

        CASE InformLicView2

    END SELECT
END SUB

SUB __UI_FocusOut (id AS LONG)
    SELECT CASE id
        CASE InformLicView

        CASE QB64LicViewPg

        CASE InformLicView2

    END SELECT
END SUB

SUB __UI_MouseDown (id AS LONG)
    SELECT CASE id
        CASE LicensesWindow

        CASE Label1

        CASE InformLicView

        CASE Label2

        CASE QB64LicViewPg

        CASE ZincLicense

        CASE InformLicView2

    END SELECT
END SUB

SUB __UI_MouseUp (id AS LONG)
    SELECT CASE id
        CASE LicensesWindow

        CASE Label1

        CASE InformLicView

        CASE Label2

        CASE QB64LicViewPg

        CASE ZincLicense

        CASE InformLicView2

    END SELECT
END SUB

SUB __UI_KeyPress (id AS LONG)
    SELECT CASE id
        CASE InformLicView

        CASE QB64LicViewPg

        CASE InformLicView2

    END SELECT
END SUB

SUB __UI_TextChanged (id AS LONG)
    SELECT CASE id
    END SELECT
END SUB

SUB __UI_ValueChanged (id AS LONG)
    SELECT CASE id
    END SELECT
END SUB

